dataset: hf           # [hf, hm, mf mm]
weights: auto         # auto or {'spectrum': 0.2, 'graph': 0.1, 'decimal': 0.1, 'onehot': 0.3, 'chemical': 0.3}
IR: 10                # Imbalanced Ratio(IR) = number of Neg. : number of Pos. Split negative samples into {IR} subsets. 10 for dataset hf and hm, 9 for dataset mf, mm.
weight_of_random_forest: 0.5
weight_of_logistic_regression: 0.5